#!/bin/sh

args="$@"

args="$@ -p 80"

file=/data/db.json
if [ -f $file ]; then
    echo "Un fichier db.json est présent"
    args="$args db.json"
fi

file=/data/file.js
if [ -f $file ]; then
    echo "Un fichier file.js est présent"
    args="$args file.js"
fi

json-server $args
